/**
 * @fileoverview gRPC-Web generated client stub for com.orientsec.demo
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.2
// source: greeter.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.com = {};
proto.com.orientsec = {};
proto.com.orientsec.demo = require('./greeter_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.orientsec.demo.GreeterClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.orientsec.demo.GreeterPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.orientsec.demo.GreeterRequest,
 *   !proto.com.orientsec.demo.GreeterReply>}
 */
const methodDescriptor_Greeter_sayHello = new grpc.web.MethodDescriptor(
  '/com.orientsec.demo.Greeter/sayHello',
  grpc.web.MethodType.UNARY,
  proto.com.orientsec.demo.GreeterRequest,
  proto.com.orientsec.demo.GreeterReply,
  /**
   * @param {!proto.com.orientsec.demo.GreeterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.orientsec.demo.GreeterReply.deserializeBinary
);


/**
 * @param {!proto.com.orientsec.demo.GreeterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.orientsec.demo.GreeterReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.orientsec.demo.GreeterReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.orientsec.demo.GreeterClient.prototype.sayHello =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.orientsec.demo.Greeter/sayHello',
      request,
      metadata || {},
      methodDescriptor_Greeter_sayHello,
      callback);
};


/**
 * @param {!proto.com.orientsec.demo.GreeterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.orientsec.demo.GreeterReply>}
 *     Promise that resolves to the response
 */
proto.com.orientsec.demo.GreeterPromiseClient.prototype.sayHello =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.orientsec.demo.Greeter/sayHello',
      request,
      metadata || {},
      methodDescriptor_Greeter_sayHello);
};


module.exports = proto.com.orientsec.demo;

